Update code to compatible with last version alpaca
get error:
KeyError: 'AXP'
AttributeError: 'DataFrame' object has no attribute 'time'

because code no update with last version of alpacahq/alpaca-trade-api-python